variable "aws_region" {
  description = "AWS region for all resources"
  type        = string
  default     = "us-east-1"
}

variable "environment" {
  description = "Environment name (e.g., dev, staging, production)"
  type        = string
  default     = "production"
}

variable "project_name" {
  description = "Project name used for resource naming"
  type        = string
  default     = "zendesk-sme-finder"
}

# Secrets Configuration
variable "zendesk_domain" {
  description = "Zendesk domain (e.g., yourcompany.zendesk.com)"
  type        = string
  sensitive   = true
}

variable "zendesk_email" {
  description = "Zendesk API user email"
  type        = string
  sensitive   = true
}

variable "zendesk_api_token" {
  description = "Zendesk API token"
  type        = string
  sensitive   = true
}

variable "slack_bot_token" {
  description = "Slack bot OAuth token"
  type        = string
  sensitive   = true
}

variable "slack_team_url" {
  description = "Slack workspace URL"
  type        = string
  sensitive   = true
}

# Bedrock Agent Configuration
variable "bedrock_model_id" {
  description = "Bedrock foundation model ID for the agent"
  type        = string
  default     = "anthropic.claude-sonnet-4-5-20250929-v1:0"
}

variable "bedrock_embedding_model_id" {
  description = "Bedrock embedding model ID for Knowledge Bases"
  type        = string
  default     = "amazon.titan-embed-text-v2:0"
}

variable "enable_bedrock_agent" {
  description = "Whether to create Bedrock Agent via Terraform (true) or manually (false)"
  type        = bool
  default     = true
}

variable "enable_knowledge_bases" {
  description = "Whether to create Knowledge Bases via Terraform (true) or manually (false)"
  type        = bool
  default     = true
}

# Deprecated: These are now auto-generated by Terraform
# Kept for backward compatibility
variable "bedrock_agent_id" {
  description = "Bedrock Agent ID (deprecated - now auto-generated)"
  type        = string
  default     = ""
}

variable "bedrock_agent_alias_id" {
  description = "Bedrock Agent Alias ID (deprecated - now auto-generated)"
  type        = string
  default     = ""
}

# S3 Configuration (Deprecated - now auto-managed by Terraform)
# Bucket is now created automatically by s3_data.tf
variable "tickets_s3_bucket" {
  description = "S3 bucket for tickets data (deprecated - now auto-created)"
  type        = string
  default     = ""
}

variable "tickets_s3_prefix" {
  description = "S3 prefix/folder for tickets data"
  type        = string
  default     = "tickets/"
}

variable "certificates_s3_bucket" {
  description = "S3 bucket for FDE certificates/profiles data (deprecated - now auto-created)"
  type        = string
  default     = ""
}

variable "certificates_s3_prefix" {
  description = "S3 prefix/folder for certificates data"
  type        = string
  default     = "fde-profiles/"
}

# Knowledge Base Configuration
variable "kb_chunking_strategy" {
  description = "Chunking strategy for Knowledge Bases (FIXED_SIZE, HIERARCHICAL, SEMANTIC, NONE)"
  type        = string
  default     = "FIXED_SIZE"
}

variable "kb_chunk_max_tokens" {
  description = "Maximum tokens per chunk for Knowledge Base chunking"
  type        = number
  default     = 300
}

variable "kb_chunk_overlap_percentage" {
  description = "Overlap percentage between chunks for Knowledge Base"
  type        = number
  default     = 20
}

# Lambda Configuration
variable "lambda_runtime" {
  description = "Lambda runtime version"
  type        = string
  default     = "python3.11"
}

variable "lambda_timeout" {
  description = "Lambda function timeout in seconds"
  type        = number
  default     = 60
}

variable "orchestration_lambda_timeout" {
  description = "Orchestration Lambda timeout in seconds"
  type        = number
  default     = 120
}

variable "lambda_memory_size" {
  description = "Lambda function memory size in MB"
  type        = number
  default     = 512
}

variable "orchestration_lambda_memory_size" {
  description = "Orchestration Lambda memory size in MB"
  type        = number
  default     = 1024
}

# API Gateway Configuration
variable "api_throttle_rate_limit" {
  description = "API Gateway throttle rate limit (requests per second)"
  type        = number
  default     = 10
}

variable "api_throttle_burst_limit" {
  description = "API Gateway throttle burst limit"
  type        = number
  default     = 20
}

variable "api_quota_limit" {
  description = "API Gateway monthly quota limit"
  type        = number
  default     = 10000
}

# VPC and Networking Configuration
variable "vpc_cidr" {
  description = "CIDR block for VPC"
  type        = string
  default     = "10.0.0.0/16"
}

# ECS Configuration
variable "ecs_task_cpu" {
  description = "ECS task CPU units (256, 512, 1024, 2048, 4096)"
  type        = string
  default     = "512"
}

variable "ecs_task_memory" {
  description = "ECS task memory in MB (512, 1024, 2048, 4096, 8192)"
  type        = string
  default     = "1024"
}

variable "ecs_desired_count" {
  description = "Desired number of ECS tasks"
  type        = number
  default     = 1
}

variable "ecs_min_capacity" {
  description = "Minimum number of ECS tasks for auto-scaling"
  type        = number
  default     = 1
}

variable "ecs_max_capacity" {
  description = "Maximum number of ECS tasks for auto-scaling"
  type        = number
  default     = 4
}

# Tags
variable "additional_tags" {
  description = "Additional tags to apply to all resources"
  type        = map(string)
  default     = {}
}
